site_name = "moat"
base_path = "/moat"
logo = "_static/logo.svg"
favicon = "_static/favicon.svg"
footer_text = "© [oddship](https://github.com/oddship) 2026"
disable_moat_citation = false

[highlight]
light = "github"
dark  = "github-dark"

[[links]]
title = "GitHub"
url = "https://github.com/oddship/moat"
icon = "github"

[[topnav]]
title = "Quickstart"
url = "/guide/quickstart/"

[[topnav]]
title = "Reference"
url = "/reference/github-actions/"

[[topnav_more]]
title = "GitHub"
url = "https://github.com/oddship/moat"
icon = "github"

[feed]
enabled = true
link = "https://oddship.github.io/moat"

[extra]
tagline = "docs are your project's moat"
